version: '3.8'
services:
  db:
    container_name: pg_container_hotel
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: forma
      POSTGRES_PASSWORD: samsamsam
      POSTGRES_DB: hotel
    ports:
      - "5434:5432"
    networks:
      - postgres-hotel-network

  pgadmin:
    container_name: pgadmin4_container_hotel
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: samsamsam
    ports:
      - "5051:80"
    depends_on:
      - db
    networks:
      - postgres-hotel-network

networks:
  postgres-hotel-network:
    driver: bridge
